[package]
org = "oasis"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
path = "./libs/document-extractor.jar"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.16.1"

[[dependency]]
org = "ballerinax"
name = "postgresql.driver"
version = "1.6.0"
