[package]
org = "oasis"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path = "./libs/document-extractor.jar"

[[platform.java17.dependency]]
path = "./libs/postgresql-42.7.2.jar"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.11.0"
